const _chIntCnf = {
  bubble: {
    bubble_enabled: true,
    bubble_bg: "#ffffff",
    bubble_image:
      "//cdn.shopify.com/s/files/1/0055/4044/6280/files/Frame_47.png?v=1602764360",
    bubble_position: "bubble-left",
    bubble_size: "5rem",
    speech_bubble_bg: "#ffffff",
    speech_bubble_cta_background: "#231F20",
    speech_bubble_text_color: "#231F20",
    pull_bubble_text:
      "Zwischendurch per Mobile über Whats App, oder über unser Kontaktformular. Ich beantworte dir gerne deine Rückfragen.",
    pull_bubble_action_url: "qwe",
    pull_bubble_button_label: "Schreib uns",
    pull_bubble_cta_text_color: "#ffffff",
    push_bubble_text: "Hey! You look great today!",
    push_bubble_close_timer: "2.5",
    push_bubble_timer: "1.5",
  },
};

const newsletterConfig = {
  enabled: true,
  selector: '[data-charles="charles-newsletter"]',
  title: "Configured Heading",
  description: "Configured Desc",
};

const Shopify = {
  Checkout: {
    Autocomplete: false,
    apiHost: "hey-charles-dev-store-2.myshopify.com",
    assetsPath: "//cdn.shopify.com/shopifycloud/shopify",
    DefaultAddressFormat:
      "{firstName}{lastName}_{company}_{address1}_{address2}_{city}_{country}{province}{zip}_{phone}",
    geolocatedAddress: {
      lat: 52.637699999999995,
      lng: 13.216100000000012,
    },
    i18n: {
      orders: {
        order_updates: {
          title: "Order updates",
        },
        complete_order: "Complete order",
        pay_now: "Pay now",
      },
      shipping_line: {
        pickup_in_store_label: "Pickup",
        no_pickup_location:
          "Your order isn't available for pickup. Enter a shipping address.",
        shipping_label: "Shipping",
        shipping_default_value: "Calculated at next step",
        shipping_free_value: "Free",
      },
      continue_button: {
        continue_to_shipping_method: "Continue to shipping",
        continue_to_payment_method: "Continue to payment",
      },
      qr_code: {
        title: "Track on your phone",
        subtitle: "Scan the code with your phone’s camera to track with Shop.",
        send_link_to_phone: "Or send a link to your phone",
      },
    },
    locale: "en",
    normalizedLocale: "en",
    moneyFormat: "€{{amount_with_comma_separator}}",
    page: "thank_you",
    releaseStage: "production",
    deployStage: "production",
    requiresShipping: true,
    step: "thank_you",
    token: "0c65bea713be122e4b755858e9c288d4",
    currency: "EUR",
    estimatedPrice: 98,
    dynamicCheckoutPaymentInstrumentsConfig: {
      paymentInstruments: {
        accessToken: "bb2b625389fd2d1fb6fd7d196a62a81a",
        amazonPayConfig: null,
        applePayConfig: null,
        checkoutConfig: {
          domain: "hey-charles-dev-store-2.myshopify.com",
          shopId: 45019463829,
        },
        shopifyPayConfig: {
          domain: "hey-charles-dev-store-2.myshopify.com",
          shopId: 45019463829,
          accelerated: false,
          supportsLogin: true,
          experimentTestGroup: false,
          merchantId: "gid://shopify/Shop/45019463829",
          supportsSubscriptions: false,
        },
        currency: "EUR",
        googlePayConfig: {
          dynamicBuyFlow: true,
          iframeSrc:
            "https://checkout.shopify.com/45019463829/sandbox/costanza_google_pay_iframe",
          currency: "EUR",
          countryCode: "DE",
          capabilities: {
            environment: "TEST",
            allowedPaymentMethods: [
              {
                type: "CARD",
                parameters: {
                  allowedAuthMethods: ["PAN_ONLY", "CRYPTOGRAM_3DS"],
                  allowedCardNetworks: ["VISA", "MASTERCARD", "AMEX"],
                  allowPrepaidCards: false,
                  billingAddressRequired: true,
                  billingAddressParameters: {
                    format: "FULL",
                    phoneNumberRequired: true,
                  },
                },
                tokenizationSpecification: {
                  type: "PAYMENT_GATEWAY",
                  parameters: {
                    gateway: "shopify",
                    gatewayMerchantId: "45019463829",
                  },
                },
              },
            ],
            existingPaymentMethodRequired: true,
            merchantInfo: {
              merchantId: "16708973830884969730",
              merchantName: "hey-charles-dev-store-2",
              merchantOrigin: "hey-charles-dev-store-2.myshopify.com",
              authJwt:
                "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJtZXJjaGFudElkIjoiMTY3MDg5NzM4MzA4ODQ5Njk3MzAiLCJtZXJjaGFudE9yaWdpbiI6ImhleS1jaGFybGVzLWRldi1zdG9yZS0yLm15c2hvcGlmeS5jb20iLCJpYXQiOjE2MzE4MDU3NjV9.BSkQQnLZ4lcffi9tRkCopnSo2mbfJXzTSLbs-XRy8SIBL99VoqgBgjm5VmAm1kz8kVxRwLMCL-anAA3UE0E5aA",
            },
            emailRequired: true,
            shippingAddressRequired: true,
            shippingAddressParameters: {
              phoneNumberRequired: true,
              allowedCountryCodes: [
                "AC",
                "AD",
                "AE",
                "AF",
                "AG",
                "AI",
                "AL",
                "AM",
                "AO",
                "AR",
                "AT",
                "AU",
                "AW",
                "AX",
                "AZ",
                "BA",
                "BB",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "BL",
                "BM",
                "BN",
                "BO",
                "BQ",
                "BR",
                "BS",
                "BT",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CC",
                "CD",
                "CF",
                "CG",
                "CH",
                "CI",
                "CK",
                "CL",
                "CM",
                "CN",
                "CO",
                "CR",
                "CV",
                "CW",
                "CX",
                "CY",
                "CZ",
                "DE",
                "DJ",
                "DK",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "EH",
                "ER",
                "ES",
                "ET",
                "FI",
                "FJ",
                "FK",
                "FO",
                "FR",
                "GA",
                "GB",
                "GD",
                "GE",
                "GF",
                "GG",
                "GH",
                "GI",
                "GL",
                "GM",
                "GN",
                "GP",
                "GQ",
                "GR",
                "GS",
                "GT",
                "GW",
                "GY",
                "HK",
                "HN",
                "HR",
                "HT",
                "HU",
                "ID",
                "IE",
                "IL",
                "IM",
                "IN",
                "IO",
                "IQ",
                "IS",
                "IT",
                "JE",
                "JM",
                "JO",
                "JP",
                "KE",
                "KG",
                "KH",
                "KI",
                "KM",
                "KN",
                "KR",
                "KW",
                "KY",
                "KZ",
                "LA",
                "LB",
                "LC",
                "LI",
                "LK",
                "LR",
                "LS",
                "LT",
                "LU",
                "LV",
                "LY",
                "MA",
                "MC",
                "MD",
                "ME",
                "MF",
                "MG",
                "MK",
                "ML",
                "MM",
                "MN",
                "MO",
                "MQ",
                "MR",
                "MS",
                "MT",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NC",
                "NE",
                "NF",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "NR",
                "NU",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PF",
                "PG",
                "PH",
                "PK",
                "PL",
                "PM",
                "PN",
                "PS",
                "PT",
                "PY",
                "QA",
                "RE",
                "RO",
                "RS",
                "RU",
                "RW",
                "SA",
                "SB",
                "SC",
                "SD",
                "SE",
                "SG",
                "SH",
                "SI",
                "SJ",
                "SK",
                "SL",
                "SM",
                "SN",
                "SO",
                "SR",
                "SS",
                "ST",
                "SV",
                "SX",
                "SZ",
                "TA",
                "TC",
                "TD",
                "TF",
                "TG",
                "TH",
                "TJ",
                "TK",
                "TL",
                "TM",
                "TN",
                "TO",
                "TR",
                "TT",
                "TV",
                "TW",
                "TZ",
                "UA",
                "UG",
                "UM",
                "US",
                "UY",
                "UZ",
                "VA",
                "VC",
                "VE",
                "VG",
                "VN",
                "VU",
                "WF",
                "WS",
                "XK",
                "YE",
                "YT",
                "ZA",
                "ZM",
                "ZW",
              ],
            },
          },
        },
        locale: "en",
        paypalConfig: null,
        offsiteConfigs: null,
        supportsDiscounts: false,
        supportsGiftCards: false,
        checkoutDisabled: false,
      },
    },
    applePayConfig: null,
    hasSellingPlan: false,
    requiresConfirmationStep: false,
    cartToken: "0fc2fab7552639deac7a58df3b3ded5e",
    OrderStatus: {},
  },
  houseNumberNudgeCountries: [
    "AU",
    "AT",
    "BR",
    "CA",
    "DE",
    "IT",
    "MX",
    "NL",
    "ES",
    "CH",
    "US",
  ],
  autocompleteEnabledCountries: [
    "AU",
    "AT",
    "BE",
    "BR",
    "CA",
    "DK",
    "FR",
    "DE",
    "HK",
    "IN",
    "IT",
    "JP",
    "LU",
    "NL",
    "NZ",
    "SG",
    "ES",
    "CH",
    "US",
  ],
  clientAttributesCollectionEventName: "client_attributes_checkout",
  shop: "hey-charles-dev-store-2.myshopify.com",
  locale: "en",
  currency: {
    active: "EUR",
    rate: "1.0",
  },
  country: "DE",
  theme: {
    name: "Debut",
    id: 107368415381,
    theme_store_id: 796,
    role: "main",
    handle: "null",
    style: {
      id: null,
      handle: null,
    },
  },
  cdnHost: "cdn.shopify.com",
  checkout: {
    created_at: "2021-09-16T17:21:40+02:00",
    currency: "EUR",
    customer_id: 4157714235541,
    customer_locale: "en",
    email: null,
    location_id: null,
    order_id: 4108036079765,
    payment_due: "98.00",
    payment_url: "https://deposit.us.shopifycs.com/sessions",
    phone: "+4915901093527",
    presentment_currency: "EUR",
    reservation_time: null,
    reservation_time_left: 0,
    requires_shipping: true,
    source_name: "checkout_next",
    source_identifier: null,
    source_url: null,
    subtotal_price: "98.00",
    taxes_included: true,
    tax_exempt: false,
    tax_lines: [
      {
        price: "15.65",
        rate: 0.19,
        title: "DE MwSt",
        channel_liable: false,
      },
    ],
    token: "0c65bea713be122e4b755858e9c288d4",
    total_price: "98.00",
    total_price_set: {
      shop_money: {
        amount: "98.0",
        currency_code: "EUR",
      },
      presentment_money: {
        amount: "98.0",
        currency_code: "EUR",
      },
    },
    total_tax: "15.65",
    updated_at: "2021-09-16T17:22:45+02:00",
    version: "edge",
    line_items: [
      {
        id: "4ca445989d6070b7a0dbc20363e26976",
        key: "4ca445989d6070b7a0dbc20363e26976",
        product_id: 5552773660821,
        variant_id: 35539064357013,
        sku: "",
        vendor: "hey-charles-dev-store-2",
        title:
          "Awesome T-Shirt with a Very Very Very Very Very Long Subscription",
        variant_title: "Xl / Blue",
        image_url:
          "https://cdn.shopify.com/s/files/1/0450/1946/3829/products/65charleswithdog.jpg?v=1603809162",
        taxable: true,
        requires_shipping: true,
        gift_card: false,
        price: "98.00",
        compare_at_price: null,
        line_price: "98.00",
        properties: {},
        quantity: 1,
        grams: 0,
        fulfillment_service: "manual",
        applied_discounts: [],
        discount_allocations: [],
        tax_lines: [
          {
            price: "15.65",
            rate: 0.19,
            title: "DE MwSt",
            channel_liable: false,
          },
        ],
      },
    ],
    gift_cards: [],
    shipping_rate: {
      handle: "shopify-Torstr.%2092-0.00",
      price: "0.00",
      title: "Torstr. 92",
      tax_lines: [
        {
          price: "0.00",
          rate: 0.19,
          title: "DE MwSt",
          channel_liable: false,
        },
      ],
    },
    shipping_address: null,
    credit_card: {
      first_name: "Nick",
      last_name: "Voelekr",
      first_digits: "424242",
      last_digits: "4242",
      brand: "visa",
      expiry_month: 4,
      expiry_year: 2025,
      customer_id: 4157714235541,
    },
    billing_address: {
      id: 9267360104597,
      first_name: "Nick",
      last_name: "Völker",
      phone: "01590 1093527",
      company: null,
      address1: "gartenstr 87",
      address2: "",
      city: "Berlin",
      province: null,
      province_code: null,
      country: "Germany",
      country_code: "DE",
      zip: "10115",
    },
    discount: null,
  },
  ClientAttributesCollection: {
    trekkie: {
      integrations: [
        {
          options: {
            appName: "checkout",
            development: false,
            defaultAttributes: {
              shopId: 45019463829,
              isMerchantRequest: null,
              themeId: 107368415381,
              themeCityHash: "4156107706133588516",
              contentLanguage: "en",
              currency: "EUR",
              checkoutToken: "0c65bea713be122e4b755858e9c288d4",
            },
            isServerSideCookieWritingEnabled: true,
            expectS2SEventId: true,
            expectS2SEventEmit: true,
          },
          defaultAttributes: {
            shopId: 45019463829,
            isMerchantRequest: null,
            themeId: 107368415381,
            themeCityHash: "4156107706133588516",
            contentLanguage: "en",
            currency: "EUR",
            checkoutToken: "0c65bea713be122e4b755858e9c288d4",
            appName: "checkout",
            uniqToken: "5d9d10f9-8f41-4890-af93-6000ee5f0899",
            visitToken: "ccb20afd-4cf1-4007-9d79-24eedfe65da1",
            microSessionId: "ef33ff28-0184-40A4-C107-37AB939866C8",
            microSessionCount: 5,
            isPersistentCookie: true,
          },
        },
        {
          options: {},
          trekkie: {
            options: {
              appName: "checkout",
              development: false,
              defaultAttributes: {
                shopId: 45019463829,
                isMerchantRequest: null,
                themeId: 107368415381,
                themeCityHash: "4156107706133588516",
                contentLanguage: "en",
                currency: "EUR",
                checkoutToken: "0c65bea713be122e4b755858e9c288d4",
              },
              isServerSideCookieWritingEnabled: true,
              expectS2SEventId: true,
              expectS2SEventEmit: true,
            },
            defaultAttributes: {
              shopId: 45019463829,
              isMerchantRequest: null,
              themeId: 107368415381,
              themeCityHash: "4156107706133588516",
              contentLanguage: "en",
              currency: "EUR",
              checkoutToken: "0c65bea713be122e4b755858e9c288d4",
              appName: "checkout",
              uniqToken: "5d9d10f9-8f41-4890-af93-6000ee5f0899",
              visitToken: "ccb20afd-4cf1-4007-9d79-24eedfe65da1",
              microSessionId: "ef33ff28-0184-40A4-C107-37AB939866C8",
              microSessionCount: 5,
              isPersistentCookie: true,
            },
          },
          timestampManager: {},
          campaignManager: {},
        },
        {
          options: {
            facebookAppPixelId: "",
            facebookCapiEnabled: false,
            agent: "shopify",
          },
          shopId: 45019463829,
          checkoutToken: "0c65bea713be122e4b755858e9c288d4",
          visitToken: "ccb20afd-4cf1-4007-9d79-24eedfe65da1",
          uniqueToken: "5d9d10f9-8f41-4890-af93-6000ee5f0899",
          appName: "checkout",
          pageID: "ef33ff2e-604D-4437-691A-8E959F3B3F89",
        },
      ],
      eventNameToEventIdMapping: {},
      config: {
        Trekkie: {
          appName: "checkout",
          development: false,
          defaultAttributes: {
            shopId: 45019463829,
            isMerchantRequest: null,
            themeId: 107368415381,
            themeCityHash: "4156107706133588516",
            contentLanguage: "en",
            currency: "EUR",
            checkoutToken: "0c65bea713be122e4b755858e9c288d4",
          },
          isServerSideCookieWritingEnabled: true,
          expectS2SEventId: true,
          expectS2SEventEmit: true,
        },
        "Session Attribution": {},
        S2S: {
          facebookCapiEnabled: false,
        },
        initialDocumentCookie:
          "_y=5d9d10f9-8f41-4890-af93-6000ee5f0899; _shopify_y=5d9d10f9-8f41-4890-af93-6000ee5f0899; __ssid=f441ebf6-2fb9-431c-97ea-f4243edc372d; _ab=1; cart_currency=EUR; _s=ccb20afd-4cf1-4007-9d79-24eedfe65da1; _shopify_s=ccb20afd-4cf1-4007-9d79-24eedfe65da1; _shopify_sa_p=; shopify_pay_redirect=pending; dynamic_checkout_shown_on_cart=1; _shopify_sa_t=2021-09-16T15%3A22%3A41.571Z; _shopify_evids=pv%3D399c73252c71f7540adfc25a6edadd1119359eb1d7e93cfc190f83467bdbc32f%3Bco%3D1769d50aeb9ddab7c0337661fb875d938253740f962de0c3c12d73d1bcfa0cbf",
      },
      navigationInfo: {
        navigationType: "reload",
        navigationApi: "PerformanceNavigationTiming",
      },
      trekkie: {
        options: {
          appName: "checkout",
          development: false,
          defaultAttributes: {
            shopId: 45019463829,
            isMerchantRequest: null,
            themeId: 107368415381,
            themeCityHash: "4156107706133588516",
            contentLanguage: "en",
            currency: "EUR",
            checkoutToken: "0c65bea713be122e4b755858e9c288d4",
          },
          isServerSideCookieWritingEnabled: true,
          expectS2SEventId: true,
          expectS2SEventEmit: true,
        },
        defaultAttributes: {
          shopId: 45019463829,
          isMerchantRequest: null,
          themeId: 107368415381,
          themeCityHash: "4156107706133588516",
          contentLanguage: "en",
          currency: "EUR",
          checkoutToken: "0c65bea713be122e4b755858e9c288d4",
          appName: "checkout",
          uniqToken: "5d9d10f9-8f41-4890-af93-6000ee5f0899",
          visitToken: "ccb20afd-4cf1-4007-9d79-24eedfe65da1",
          microSessionId: "ef33ff28-0184-40A4-C107-37AB939866C8",
          microSessionCount: 5,
          isPersistentCookie: true,
        },
      },
    },
    checkoutToken: "0c65bea713be122e4b755858e9c288d4",
  },
};

export { Shopify, _chIntCnf, newsletterConfig };
